// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "a04e276182d50c1d1ab9fa244cef850a"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"1c3c6482a95e616e1bd0fd8088035ef2": "1f8b08000000000000ffb25174f1770e890c7055c828c9cdb1e3b201510a398979e9b64a59894a765cd5d57a1ea98929b5b55c3649f929956001a7fc944a90803e44c4461fac17100000ffffb90553424b000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("MyBox", "templates")
		b.SetResolver("index.html", packr.Pointer{ForwardBox: gk, ForwardPath: "1c3c6482a95e616e1bd0fd8088035ef2"})
		}()

	return nil
}()
